const stateList = [

    { value: "See All", title: "See All" },
    { value: 'Alabama', title: 'Alabama' },
    { value: 'Alaska', title: 'Alaska' },
    { value: 'American Samoa', title: 'American Samoa' },
    { value: 'Arizona', title: 'Arizona' },
    { value: 'Arkansas', title: 'Arkansas' },
    { value: 'Baker Island', title: 'Baker Island' },
    { value: 'California', title: 'California' },
    { value: 'Colorado', title: 'Colorado' },
    { value: 'Connecticut', title: 'Connecticut' },
    { value: 'Delaware', title: 'Delaware' },
    { value: 'District of Columbia', title: 'District of Columbia' },
    { value: 'Florida', title: 'Florida' },
    { value: 'Georgia', title: 'Georgia' },
    { value: 'Guam', title: 'Guam' },
    { value: 'Hawaii', title: 'Hawaii' },
    { value: 'Howland Island', title: 'Howland Island' },
    { value: 'Idaho', title: 'Idaho' },
    { value: 'Illinois', title: 'Illinois' },
    { value: 'Indiana', title: 'Indiana' },
    { value: 'Iowa', title: 'Io' },
    { value: 'Jarvis Island', title: 'Jarvis Island' },
    { value: 'Johnston Atoll', title: 'Johnston Atoll' },
    { value: 'Kansas', title: 'Kansas' },
    { value: 'Kentucky', title: 'Kentucky' },
    { value: 'Kingman Reef', title: 'Kingman Reef' },
    { value: 'Louisiana', title: 'Louisiana' },
    { value: 'Maine', title: 'Maine' },
    { value: 'Maryland', title: 'Maryland' },
    { value: 'Massachusetts', title: 'Massachusetts' },
    { value: 'Michigan', title: 'Michigan' },
    { value: 'Midway Atoll', title: 'Midway Atoll' },
    { value: 'Minnesota', title: 'Minnesota' },
    { value: 'Mississippi', title: 'Mississippi' },
    { value: 'Missouri', title: 'Missouri' },
    { value: 'Montana', title: 'Montana' },
    { value: 'Navassa Island', title: 'Navassa Island' },
    { value: 'Nebraska', title: 'Nebraska' },
    { value: 'Nevada', title: 'Nevada' },
    { value: 'New Hampshire', title: 'New Hampshire' },
    { value: 'New Jersey', title: 'New Jersey' },
    { value: 'New Mexico', title: 'New Mexico' },
    { value: 'New York', title: 'New York' },
    { value: 'North Carolina', title: 'North Carolina' },
    { value: 'North Dakota', title: 'North Dakota' },
    { value: 'Northern Mariana Islands', title: 'Northern Mariana Islands' },
    { value: 'Ohio', title: 'Ohio' },
    { value: 'Oklahoma', title: 'Oklahoma' },
    { value: 'Oregon', title: 'Oregon' },
    { value: 'Palmyra Atoll', title: 'Palmyra Atoll' },
    { value: 'Pennsylvania', title: 'Pennsylvania' },
    { value: 'Puerto Rico', title: 'Puerto Rico' },
    { value: 'Rhode Island', title: 'Rhode Island' },
    { value: 'South Carolina', title: 'South Carolina' },
    { value: 'South Dakota', title: 'South Dakota' },
    { value: 'Tennessee', title: 'Tennessee' },
    { value: 'Texas', title: 'Texas' },
    { value: 'United States Minor Outlying Islands', title: 'United States Minor Outlying Islands' },
    { value: 'United States Virgin Islands', title: 'United States Virgin Islands' },
    { value: 'Utah', title: 'Utah' },
    { value: 'Vermont', title: 'Vermont' },
    { value: 'Virginia', title: 'Virginia' },
    { value: 'Wake Island', title: 'Wake Island' },
    { value: 'Washington', title: 'Washington' },
    { value: 'West Virginia', title: 'West Virginia' },
    { value: 'Wisconsin', title: 'Wisconsin' },
    { value: 'Wyoming', title: 'Wyoming' },
];

export default stateList;